application:
  name: lg_server
  port: 8630
debug: true
kafka:
  topic: ["XXX"]
  group_id: "XXX"
  bootstrap_servers: "XXX:XX,XXX:XX,XXX:XX"
  security_protocol: "PLAINTEXT"
  sasl_mechanism: "PLAIN"
  sasl_username: "XXX"
  sasl_password: "XXX"
database:
  db_type: "mysql"
  dsn: ""
#  dsn: "user=postgres password= host=127.0.0.1 port=8432 dbname= sslmode=disable TimeZone=Asia/Shanghai"
  charset: "utf-8"
  log_mode: "info"
  max_idle_conn: 10
  max_open_conn: 100
redis:
  endpoints:
    - ""
  password: ""
  index_db: 0
  MinIdleConns: 10
  max_idle_conns: 50
  max_active_conns: 10
  max_retry_times: 5
  master_name:
  sentinel_username:
  sentinel_password:
rabbitmq:
  host:
  port: 8672
  username: lucas
  password:
crypto:
  - type: aes
    key: ""
  - type: des
    key: ""
log:
  # 是否写入文件
  write_file: true
  # true|false
  json_log: false
  # error|warn|info|debug
  log_level: debug
  # 文件配置
  log_file_conf:
    log_file_path: ./log/cartl.log
    max_size: 10
    max_age: 28
    max_backups: 100
    compress: false