basePath: /lg_server/api
host: localhost:8080
info:
  contact:
    email: 1783022886@qq.com
    name: lucas
    url: http://www.swagger.io/support
  description: 封装ETL处理逻辑，降低数据治理门槛
  title: ETL计算引擎服务
  version: "1.0"
paths:
  /health-check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 健康检查
      tags:
      - 健康检查
swagger: "2.0"
